### ISSUE TITLE
Wifi modülünde sorun

### ISSUE THREAD

**Issue by gokturkDev** [deneyapkart/deneyapkart-arduino-core#11]
Merhabalar, 

Deneyap kartımda bir web sunucusu oluşturmak istedim.
Sitedeki https://deneyapkart.org/proje-118.html bu projedeki kodu, Android IDE me yapıştırdım ve compilelamayı denedim ancak şu hata ile karşılaştım

![image](https://user-images.githubusercontent.com/87906890/146264597-22d6c608-8bc0-4d33-a95c-9acf9f2dffd7.png)

Biraz incelemeden sonra WifiESP32.h nin gerçekten bu dizinde olmadığını farkettim
![image](https://user-images.githubusercontent.com/87906890/146264805-9f84518e-32f0-4bbe-a5bb-34b9c83056dc.png)

Daha sonra internette farklı bir çözüm arayışına girdim ve şu tutorial i buldum
https://randomnerdtutorials.com/esp32-web-server-arduino-ide/
Farkettim ki bu kod, deneyap sitesindeki tutoriali oluşturan kodun boilerplate'i. 
Bu kodu Android IDE me yapıştırdım ve compilelamayı denedim ve şu hatayı aldım.

![image](https://user-images.githubusercontent.com/87906890/146265007-2ab9b18a-af4c-42f5-bea1-464a5ffc060b.png)

Biraz inceleme sonucu, IDE deki boardu, deneyap karttan ardunio UNO ya değiştirdim ve bu şekilde compilelamayı denedim ve başarılı bir şekilde compileadım

![image](https://user-images.githubusercontent.com/87906890/146265181-2557c828-6882-4999-a02f-d1bdd0e4adc8.png)

Anladığım kadarıyla, deneyap reposu Wifi modülünün outdated, eksik veya hatalı bir versiyonunu kullanmakta. Lütfen bu konuyla ilgilenebilir misiniz?

Çok teşekkürler,
Kolay gelsin

**Comment by zeynepdicle** [comment]
Merhabalar, 
Arduino IDE'de Deneyap Kütüphanesinin kaçıncı versiyon yüklü ?

**Comment by gokturkDev** [comment]
Merhaba,

Bu issueyu açmadan önce, deneyap kartın sitesindeki tutoriali çalıştırmayı denemek için daha eski bir deneyap kart versiyonuna (1.1.0) geçmiştim. Bu issueyu yazarken https://randomnerdtutorials.com/esp32-web-server-arduino-ide/ bu kodu bu versiyonda çalıştırmışım

Updateleyip versiyon 1.3.2 e geçince https://randomnerdtutorials.com/esp32-web-server-arduino-ide/ buradaki kod sorunsuz bir şekilde çalıştı
Ancak deneyap kartın sitesindeki tutorial yine derleme hatası verdi.
https://deneyapkart.org/proje-118.html

İlginiz için teşekkür ederim,
Kolay gelsin
