### ISSUE TITLE
TürkTelekom CDN engellemesi

### ISSUE THREAD

**Issue by inoaa79** [deneyapkart/deneyapkart-arduino-core#13]
Deneyap Arduino Core kart bilgisi yüklenirken bilgileri Github CDN sunucularından çekiyor, lakin TürkTelekom, SuperOnline vb. şirketler Github CDN'i engelliyor, bu sebeple çoğunlukla kart sürücüsü yüklenemiyor. Bu sebeple CDN sunucularını taşınması şart gibi.
Bkz.
 https://twitter.com/linuxgemini/status/1561679929015689216

**Comment by incyi** [comment]
Yok artik, hangi kafa bunu bloke ediyor ? Gitlab block edilmis mi mesela ?

**Comment by inoaa79** [comment]
Gitlab hakkında bir bilgi edinemedim. Lakin Deneyap eğitimleri sırasında çok yaşadığımız bir sorun oldu. Bkz. VPN'siz kuramadım çoğu cihaza.
