### ISSUE TITLE
DeneyapKart Pin Kullanım Durumu.

### ISSUE THREAD

**Issue by KaptanINO** [deneyapkart/deneyapkart-arduino-core#3]
RandomNerdTutorial sitesinde ESP32 için Pin Kullanım tablosu var. Bazı pinler DOIT ESP32 DEVKIT'de bazı pinler ( örn. 6'den 11. pine kadar kullanılamaz ) çalışmamakta veya özel kuralları/senaryoları var. Bu kaynak [ https://randomnerdtutorials.com/esp32-pinout-reference-gpios/](url) içinde bulunan pin kullanım durumları ( Tablo verdiğim sayfadaki ESP32 Peripherals başlığı altında ESP32'ye ait GPIO fotoğrafının altında bulunmaktadır.) DeneyapKart için geçerli midir?

**Comment by ozgurbostan** [comment]
Merhabalar,

Evet, tablodaki ozelliklerin hepsi herhangi bir ESP32 tabanli gelistirme karti icin gecerlidir. Sadece hangi pinin Deneyap Kart icin hangi pine denk geldigine dikkat etmek gerekmektedir. Bunun icin kutuphane icindeki deneyap.h dosyasini inceleyebilirsiniz.
